In [1]:
import numpy as np
import numpy.linalg as la

In [2]:
def funcx(x):
    fx = 100*(np.sqrt(x[0]**2+(x[1]+1)**2)-1)**2 + 90*(np.sqrt(x[0]**2+(x[1]+1)**2)-1)**2 -(20*x[0]+40*x[1])  
    return fx

In [3]:
def gradient(x,delta):
    grad=np.zeros(2)
    grad[0]=(funcx([x[0]+delta,x[1]])- funcx([x[0]-delta,x[1]]))/(2*delta)
    grad[1]=(funcx([x[0],x[1]+delta])- funcx([x[0],x[1]-delta]))/(2*delta)
    return grad

In [4]:
def golden(x,search,xi,eps):
    a = xi[0];
    b = xi[1];
    tau = 0.381967;
    alpha1 = a*(1-tau) + b*tau;
    alpha2 = a*tau + b*(1-tau);
    falpha1 = funcx(x+alpha1*search);
    falpha2 = funcx(x+alpha2*search);
    for i in range(100):
        if falpha1 > falpha2:
            a = alpha1;
            alpha1 = alpha2;
            falpha1 = falpha2;
            alpha2 = tau*a + (1-tau)*b;
            falpha2 = funcx(x+alpha2*search);
        else:
            b = alpha2;
            alpha2 = alpha1;
            falpha2 = falpha1;
            alpha1 = tau*b + (1-tau)*a;
            falpha1 = funcx(x+alpha1*search);

        if np.abs(funcx(x+alpha1*search)- funcx(x+alpha2*search)) < eps :
            break;
    return alpha1,falpha1

In [8]:
# Initialitazion 
delta=1e-3; 
ep1=1e-3; 
xi = [-1,1];
x = xi;
A=np.eye(len(x))
fx_prev=funcx(x)

#new point estimated by gradient
grad_p=gradient(x,delta)
Si = -grad_p;
alpha,fx_prev = golden(x,Si,xi,ep1)
x_c = x + alpha*Si
x_c = np.reshape(x_c,(2,1))
x = np.reshape(x,(2,1))
grad_p = np.reshape(grad_p,(2,1))
Si = np.reshape(Si,(2,1))

print("Initial function value = %f \n " % fx_prev)
print("No. \t \t x-vector \t   f(x) \t Norm Grad \n")
print("______________________________________________________________________\n")
for j in range(1):
    deltax=x_c-x
    grad_c=gradient(x_c,delta)
    grad_c=np.reshape(grad_c,(2,1))
    deltag=grad_c-grad_p
    term_1= np.matmul(deltag,deltag.transpose())/  ( np.matmul(deltag.transpose(),deltax))
    term_2= np.matmul(grad_p,grad_p.transpose())/  ( np.matmul(grad_p.transpose(),Si))
    print(term_1)
    print(term_2)
    A = A + term_1 + term_2
    Si=np.matmul(-1*la.inv(A),grad_c)
    alpha,fx_curr = golden(x_c,Si,xi,ep1);
    fx_prev=funcx(x)
    grad_p=grad_c
    x=x_c
    x_c= x +  alpha*Si
    print(Si)
    if abs(fx_curr-fx_prev)<ep1 or la.norm(grad_c)<ep1:
        break; 
    print("%d\t %f %f\t %f \t%f \n" %(j,x_c[0],x_c[1],fx_curr,la.norm(dire_c)))
print("______________________________________________________________________\n") 
print("%d\t %f %f\t %f \t%f \n" %(j,x_c[0],x_c[1],fx_curr,la.norm(dire_c)))


Initial function value = 8.942496 
 
No. 	 	 x-vector 	   f(x) 	 Norm Grad 

______________________________________________________________________

[[  77.20681272 -152.53612143]
 [-152.53612143  301.36289169]]
[[-0.2680985   0.44296918]
 [ 0.44296918 -0.7319015 ]]
[[30.15285988]
 [15.26113408]]


NameError: name 'dire_c' is not defined