In [35]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
%matplotlib qt

In [54]:
ds = pd.read_csv('Life Expectancy Data.csv')
ds = ds.dropna()
X = ds[['Schooling', ' BMI ']]
X = X.to_numpy()
y = ds['Life expectancy ']
y = y.to_numpy()
fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')
ax.scatter(X[:,0], X[:,1], y, c='r', marker='o')
ax.set_xlabel('Schooling',fontsize=12)
ax.set_ylabel('BMI',fontsize=12)
ax.set_zlabel('Life expectancy',fontsize=12)

Text(0.5, 0, 'Life expectancy')

In [56]:
#Standardization using z-score
x_b = np.c_[np.ones((len(X),1)),X]
nf,nc=x_b.shape
x_bs=x_b
for it in range(1,nc):
    m=np.mean(x_b[:,it])
    std=np.std(x_b[:,it])
    x_bs[:,it]=(x_b[:,it]-m)/std

fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')
ax.scatter(x_bs[:,1], x_bs[:,2], y, c='r', marker='o')
ax.set_xlabel('Schooling',fontsize=12)
ax.set_ylabel('BMI',fontsize=12)
ax.set_zlabel('Life expectancy',fontsize=12) 

Text(0.5, 0, 'Life expectancy')

In [70]:
N=len(y)
theta = np.array([[0],[0],[0]])
ep=1e-6
lr =1e-3
n_iter = 20000
j_cost= np.zeros([n_iter])
y=y.reshape((len(y), 1))
for it in range(n_iter):
    #Gradient
    pred = np.dot(x_bs,theta)
    h=(pred - y)
    si=-lr*(1/N)*(x_bs.T.dot(h))
    theta = theta + si;
    j_cost[it]=np.sum(np.square(h))
    
    if np.linalg.norm(si)<ep:
        print('break')
        break
print(np.linalg.norm(si))
fig = plt.figure()
plt.plot(j_cost[0:it+1])
plt.show()
print(np.c_[pred,y,h])
print("Iterations: %d" %it)
print("DG:  \n theta_0=%f \n theta_1=%f, \n theta_2=%f" %(theta[0],theta[1],theta[2]))

break
9.99581414180778e-07
[[63.68819739 65.         -1.31180261]
 [63.44963247 59.9         3.54963247]
 [63.21106754 59.9         3.31106754]
 ...
 [64.13549361 44.8        19.33549361]
 [63.71180748 45.3        18.41180748]
 [63.67617833 46.         17.67617833]]
Iterations: 15837
DG:  
 theta_0=69.302295 
 theta_1=5.422204, 
 theta_2=1.759034


In [71]:
%matplotlib qt

xc = np.arange(np.min(x_bs[:,1]), np.max(x_bs[:,1]), 0.01)
yc = np.arange(np.min(x_bs[:,2]), np.max(x_bs[:,2]), 0.01)
plane=np.zeros([len(xc),len(yc)])

for i in range(len(xc)):
    for j in range(len(yc)):
        plane[i,j]=np.dot(np.c_[1,xc[i],yc[j]],theta)
B, M = np.meshgrid(yc, xc)
fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')
surf = ax.plot_surface(B,M, plane,
                       linewidth=0, antialiased=False)
ax.scatter(x_bs[:,1], x_bs[:,2], y, c='r', marker='o')
ax.set_xlabel('Schooling',fontsize=12)
ax.set_ylabel('BMI',fontsize=12)
ax.set_zlabel('Life expectancy',fontsize=12) 

Text(0.5, 0, 'CO2')